checks:
    python:
        code_rating: true
        duplicate_code: true
tools:
    pylint:
        python_version: '3'
filter:
    excluded_paths:
        - './posos/app/tests.py*'
        - './posos/app/migrations/*'
build:
    environment:
        python: '3.5.1'
        variables:
            DJANGO_SETTINGS_MODULES: settings

    dependencies:
        override:
            - 'pip install -r requirements.txt'
            - 'pip install pycodestyle'
            - 'pip install flake8'
    tests:
        override:
            - command: pycodestyle --max-line-length=119 ./posos/app
            # - command: flake8 --max-line-length=119 ./app
