image: python:3.5.1
pipelines:
  default:
    - step:
        script:
          - pip install -r requirements.txt
          - pip install codecov
          - python posos/manage.py test app
          - coverage run --rcfile=coverage.rc posos/manage.py test
          - codecov --token 72870f79-c051-442c-8e4c-355dad2cef29
